apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    app: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: tpolak66/reverseproxy:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "500M"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
          ports:
            - containerPort: 8080
      restartPolicy: Always